import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {ConversationContext} from '../scripts/conversation-context.mjs';
import {sendText} from '../weixin-send.mjs';
const received='2026-09-13T14:50:00.000Z',sent='2026-09-13T14:48:55.000Z';
function context(t){const c=new ConversationContext(':memory:');t.after(()=>c.close());return c;}
function notice(c,fields={}){return c.recordNotification({id:'download-1',text:'Landman S01E03 已下载完成，文件在 Movies。要投电视就说一声。',source:'download',taskId:'download-landman-03',sentAt:sent,...fields});}
function incoming(c,text='投吧',id='user-1',at=received,conversation='home-agent:shared'){c.receive(text,conversation,id,'wechat',at);c.activate(id);}
test('download notice is present for 投吧 without becoming a fake user message',t=>{const c=context(t);notice(c);incoming(c);const p=c.packet('投吧');assert.equal(p.assistant_notifications[0].task_id,'download-landman-03');assert.match(p.assistant_notifications[0].text,/Landman S01E03/);assert.equal(p.recent_dialogue.length,0);assert.equal(c.recent().length,0);});
test('teacher and download notices retain identities for follow-up references',t=>{const c=context(t);notice(c,{id:'teacher-1',text:'Omar 在 Preply 回复：周二晚8点半可以。',source:'reply-watch',taskId:'watch-omar'});notice(c);incoming(c,'帮我回复 Omar');const p=c.packet('帮我回复 Omar');assert.ok(p.assistant_notifications.some(n=>n.task_id==='watch-omar'));assert.equal(p.assistant_notifications.length,2);});
test('notification arriving while a request is active cannot leak into that request, even with an older timestamp',t=>{const c=context(t);incoming(c,'关空调');notice(c);assert.equal(c.packet('关空调').assistant_notifications.length,0);c.complete('user-1','空调关闭');incoming(c,'投吧','user-2');assert.equal(c.packet('投吧').assistant_notifications.length,1);});
test('receipt cutoff excludes notifications sent after the user message',t=>{const c=context(t);notice(c,{sentAt:'2026-09-13T15:00:00Z'});incoming(c);assert.equal(c.packet('投吧').assistant_notifications.length,0);});
test('notifications cannot create or revive a working goal',t=>{const c=context(t);notice(c);incoming(c);assert.equal(c.packet('投吧').working_topics.length,0);assert.equal(c.packet('投吧').recent_closed_topics.length,0);});
test('accepted event ids deduplicate; conflicting ids are rejected',t=>{const c=context(t);assert.equal(notice(c),true);assert.equal(notice(c),false);assert.throws(()=>notice(c,{text:'different'}),/conflict/);});
test('failed and unknown deliveries are never presented as sent',t=>{const c=context(t);assert.equal(notice(c,{deliveryStatus:'unknown'}),false);assert.equal(notice(c,{deliveryStatus:'rejected'}),false);incoming(c);assert.equal(c.packet('投吧').assistant_notifications.length,0);});
test('notification history survives a fresh session and receive cursor persists',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'notice-context-'));t.after(()=>fs.rmSync(dir,{recursive:true}));let c=new ConversationContext(path.join(dir,'db'));notice(c);incoming(c);c.close();c=new ConversationContext(path.join(dir,'db'));t.after(()=>c.close());assert.equal(c.packet('投吧',{sessionId:'fresh'}).assistant_notifications.length,1);});
test('bounded notification context keeps recent notice and excludes other recipients',t=>{const c=context(t);for(let i=0;i<20;i++)notice(c,{id:'n'+i,text:'x'.repeat(9000)+i});notice(c,{id:'secret',conversation:'someone-else',text:'PRIVATE_OTHER_USER'});incoming(c);const p=c.packet('投吧');assert.ok(JSON.stringify(p).length<=6800);assert.ok(!JSON.stringify(p).includes('PRIVATE_OTHER_USER'));assert.equal(p.assistant_notifications.at(-1).id,'n19');});
test('old database migration preserves pre-existing dialogue',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'notice-migrate-'));t.after(()=>fs.rmSync(dir,{recursive:true}));const file=path.join(dir,'db');const old=new DatabaseSync(file);old.exec("CREATE TABLE turns(seq INTEGER PRIMARY KEY,id TEXT UNIQUE NOT NULL,conversation TEXT NOT NULL,received_at TEXT NOT NULL,user_text TEXT NOT NULL,assistant_text TEXT,status TEXT NOT NULL,source TEXT NOT NULL,session_id TEXT); INSERT INTO turns VALUES(1,'old','home-agent:shared','2026-09-12T00:00:00Z','old question','old answer','answered','wechat',NULL)");old.close();const c=new ConversationContext(file);t.after(()=>c.close());assert.equal(c.get('old').assistant_text,'old answer');notice(c);incoming(c);assert.equal(c.packet('投吧').recent_dialogue[0].user,'old question');});
async function withSender(t,fn){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'notice-sender-'));const state=path.join(dir,'openclaw-weixin');fs.mkdirSync(path.join(state,'accounts'),{recursive:true});fs.writeFileSync(path.join(state,'accounts.json'),'["test"]');fs.writeFileSync(path.join(state,'accounts/test.json'),JSON.stringify({token:'unit-test-token',userId:'owner'}));const keys=['OPENCLAW_STATE_DIR','WEIXIN_ACCOUNT_ID','WEIXIN_PUSH_TO','HOME_AGENT_NOTIFICATION_DB'];const old=Object.fromEntries(keys.map(k=>[k,process.env[k]]));const fetch=globalThis.fetch;process.env.OPENCLAW_STATE_DIR=dir;process.env.WEIXIN_ACCOUNT_ID='test';delete process.env.WEIXIN_PUSH_TO;process.env.HOME_AGENT_NOTIFICATION_DB=path.join(dir,'notice.db');try{await fn(process.env.HOME_AGENT_NOTIFICATION_DB);}finally{globalThis.fetch=fetch;for(const k of keys)old[k]===undefined?delete process.env[k]:process.env[k]=old[k];fs.rmSync(dir,{recursive:true});}}
test('shared sender records the exact accepted notification and source',t=>withSender(t,async file=>{let transmitted;globalThis.fetch=async(_,options)=>{transmitted=JSON.parse(options.body);return {status:200,text:async()=>'{"ret":0}'}};await sendText('Omar 回复了',{notification:{id:'watch:1',source:'reply-watch',taskId:'omar'}});const c=new ConversationContext(file);try{assert.equal(transmitted.msg.item_list[0].text_item.text,'Omar 回复了');const n=c.notificationContext('他')[0];assert.equal(n.text,'Omar 回复了');assert.equal(n.source,'reply-watch');assert.equal(n.task_id,'omar');}finally{c.close();}}));
test('shared sender does not record a business rejection or timeout',t=>withSender(t,async file=>{globalThis.fetch=async()=>({status:200,text:async()=>'{"ret":-1}'});await assert.rejects(sendText('rejected'),/rejected/);globalThis.fetch=async()=>{throw new Error('timeout')};await assert.rejects(sendText('unknown'),/unknown/);const c=new ConversationContext(file);try{assert.equal(c.notificationContext('anything').length,0);}finally{c.close();}}));
